services:
  cognito-mock:
    image: motoserver/moto:latest
    ports:
      - "5000:5000"
    environment:
      - MOTO_PORT=5000
      - MOTO_COGNITO_IDP_USER_POOL_ID_STRATEGY=HASH
      - MOTO_COGNITO_IDP_USER_POOL_CLIENT_ID_STRATEGY=HASH
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - e2e-network

  frontend:
    build:
      context: ../../frontend/apps/user
      dockerfile: ../../../e2e/config/frontend-real.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_COGNITO_ENDPOINT=http://cognito-mock:5000
      - AWS_COGNITO_ENDPOINT=http://cognito-mock:5000
    depends_on:
      - backend
      - cognito-mock
    networks:
      - e2e-network

  backend:
    build:
      context: ../../backend/services/auth-service
      dockerfile: ../../../e2e/config/backend-real.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - COGNITO_ENDPOINT=http://cognito-mock:5000
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_REGION=us-east-1
      - PORT=8080
    depends_on:
      - cognito-mock
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge